name: 'Firebase Test Lab Android Action'
description: 'A GitHub Action to test mobile applications (Android) using Firebase Test Lab.'
author: 'Asad Mansoor'
inputs:
  arg-spec:
    description: 'string of arguments.'
    required: true
outputs:
  FTL_REPORT_URL:
    description: 'Report URL'
  FTL_GCP_URL:
    description: 'Test artifacts URL'
  FTL_ERROR_MESSAGE:
    description: 'Error message'
  FTL_TEST_STATUS:
    description: 'Status of test execution'
  FTL_TEST_LOGS:
    description: 'Logs of test execution'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.arg-spec }}
branding:
  icon: 'check-square'  
  color: 'blue'